CONFIG = {
    "tickers": [
        "AAPL",
        "MSFT",
        "GOOGL",
        "AMZN",
        "NVDA",
        "META",
        "TSLA",
        "BRK-B",
        "JPM",
        "JNJ",
        "V",
        "PG",
        "UNH",
        "HD",
        "MA",
        "DIS",
        "PYPL",
        "NFLX",
        "ADBE",
        "CRM",
        "INTC",
        "VZ",
        "T",
        "PFE",
        "MRK",
        "KO",
        "PEP",
        "WMT",
    ],
    "period": "6mo",
    "interval": "1d",
    "rsi_oversold": 30,
    "rsi_overbought": 70,
    "sma_short": 20,
    "sma_long": 50,
    "min_volume": 5000000,
    "top_n": 10,
}
